### ISSUE TITLE
Docker on Sierra : Building issue

### ISSUE THREAD

**Issue by stephane-lb** [greyltc/docker-archlinux#2]
Hi,

Thanks for your work here it is really promising. Just tried to get it working here and got this : 
```
--- uncompress package: /var/folders/q8/0nk145n94lv3k76h82mv9hdc0000gn/T/tmp.83DCXzBD/dash-0.5.9.1-1-x86_64.pkg.tar.xz
--- configure DNS and pacman
/dev/fd/63: line 106: ./tmproot/etc/mtab: No such file or directory
```

However 

```
~/Projects/TestDockerArch/docker-archlinux/tmproot/etc                                                                                                  [15:04:47] 
> $ ls mtab                                                                                                                                                          mtab
```
Could you help? I am using Docker on Mac OSX Sierra. It is probably due to the absence of fakechroot on Mac.

Thanks,

Stephane

**Comment by greyltc** [comment]
~At first sight, that looks like some sort of docker install/system issue rather than a problem in my container here (maybe you ran out of disk space?).~

~Firstly, make sure docker's hello world is working on your system:
https://docs.docker.com/engine/tutorials/dockerizing/#/run-a-hello-world~

~Secondly, it's very hard for someone like me to help you troubleshoot with just snippets containing an error. I don't even see the command you ran there that generated the error! Please send the command you ran and the entire output.~

My previous comments here were mostly braindead (except for the fact that I really do need the full output to be able to help). You're not even able to get to the docker part of things here.

I've never tried to run this on anything besides Arch Linux (maybe I tested on ubuntu once). Running it on OSX is really a stretch (but it could work). Without fakechroot you're probably toast though. As you can see, my code here pulls and runs a script from one of my other repos: https://github.com/greyltc/arch-bootstrap/blob/master/arch-bootstrap.sh and that's where fakechroot gets called. fakechroot is critically important for pretending like we're the root user inside the chroot we're trying to create. I don't know if fakechroot can be made to work in apple land.

The `/etc/mtab` folder should be provided by Arch's "filesystem" package: https://www.archlinux.org/packages/core/x86_64/filesystem/ somehow that's not being extracted properly but I can't really say any more without being able to see the whole output.

**Comment by greyltc** [comment]
Closing because @stephane-lb didn't respond
